Repository chrispo-git/ult-s, pull requests merged in 2023-03, with the labels that each got.

#123 Greninja Down Special - Hydro Lick
  romfs/fighter/gekkouga/motion/body/c00/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c00/d03speciallw.nuanmb
  romfs/fighter/gekkouga/motion/body/c01/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c01/d03speciallw.nuanmb
  romfs/fighter/gekkouga/motion/body/c02/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c02/d03speciallw.nuanmb
  romfs/fighter/gekkouga/motion/body/c03/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c03/d03speciallw.nuanmb
  romfs/fighter/gekkouga/motion/body/c04/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c04/d03speciallw.nuanmb
  romfs/fighter/gekkouga/motion/body/c05/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c05/d03speciallw.nuanmb
  romfs/fighter/gekkouga/motion/body/c06/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c06/d03speciallw.nuanmb
  romfs/fighter/gekkouga/motion/body/c07/d03specialairlw.nuanmb
  romfs/fighter/gekkouga/motion/body/c07/d03speciallw.nuanmb
  src/gekkouga/mod.rs
Labels: balance change

#122 Universal Wavedash Update
  src/common/wavedash.rs
  src/lucina/mod.rs
  src/util/mod.rs
Labels: engine change

#121 Bowser Fireball Buffs
  src/koopa/mod.rs
Labels: balance change

#114 Removal of universal airdodge FaF nerf
  romfs/fighter/common/param/fighter_param_motion.prcxml
Labels: engine change

#117 Ten Degree DI
  romfs/fighter/common/param/common.prcxml
Labels: engine change

#118 Dark Samus Nair Animation fix
  romfs/fighter/samusd/motion/body/c00/c05attackairn.nuanmb
  romfs/fighter/samusd/motion/body/c01/c05attackairn.nuanmb
  romfs/fighter/samusd/motion/body/c02/c05attackairn.nuanmb
  romfs/fighter/samusd/motion/body/c03/c05attackairn.nuanmb
  romfs/fighter/samusd/motion/body/c04/c05attackairn.nuanmb
  romfs/fighter/samusd/motion/body/c05/c05attackairn.nuanmb
  romfs/fighter/samusd/motion/body/c06/c05attackairn.nuanmb
  romfs/fighter/samusd/motion/body/c07/c05attackairn.nuanmb
Labels: bug

#106 Mii Gunner Changes
  src/common/cancel.rs
  src/common/faf_change.rs
  src/miigunner/mod.rs
Labels: balance change

#116 Wolf adjustments
  src/wolf/mod.rs
Labels: balance change

#109 Inkling adjustments
  romfs/fighter/inkling/motion/body/c00/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c00/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c00/motion_list.bin
  romfs/fighter/inkling/motion/body/c01/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c01/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c01/motion_list.bin
  romfs/fighter/inkling/motion/body/c02/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c02/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c02/motion_list.bin
  romfs/fighter/inkling/motion/body/c03/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c03/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c03/motion_list.bin
  romfs/fighter/inkling/motion/body/c04/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c04/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c04/motion_list.bin
  romfs/fighter/inkling/motion/body/c05/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c05/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c05/motion_list.bin
  romfs/fighter/inkling/motion/body/c06/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c06/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c06/motion_list.bin
  romfs/fighter/inkling/motion/body/c07/c05attackairf.nuanmb
  romfs/fighter/inkling/motion/body/c07/c05attackairn.nuanmb
  romfs/fighter/inkling/motion/body/c07/motion_list.bin
  src/inkling/mod.rs
Labels: overhaul, balance change

#115 Brawler Fair Adjustments
  src/miifighter/mod.rs
Labels: balance change

#113 Corrin adjustments
  romfs/fighter/kamui/motion/body/c00/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c00/motion_list.bin
  romfs/fighter/kamui/motion/body/c01/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c01/motion_list.bin
  romfs/fighter/kamui/motion/body/c02/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c02/motion_list.bin
  romfs/fighter/kamui/motion/body/c03/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c03/motion_list.bin
  romfs/fighter/kamui/motion/body/c04/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c04/motion_list.bin
  romfs/fighter/kamui/motion/body/c05/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c05/motion_list.bin
  romfs/fighter/kamui/motion/body/c06/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c06/motion_list.bin
  romfs/fighter/kamui/motion/body/c07/c02attacklw3.nuanmb
  romfs/fighter/kamui/motion/body/c07/motion_list.bin
  src/common/faf_change.rs
  src/kamui/mod.rs
Labels: balance change

#119 Link Nair code fix
  src/link/mod.rs
Labels: bug

#120 Lucas Adjustments
  romfs/fighter/lucas/motion/body/c00/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c00/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c00/d00specialnstart.nuanmb
  romfs/fighter/lucas/motion/body/c01/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c01/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c01/d00specialnstart.nuanmb
  romfs/fighter/lucas/motion/body/c02/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c02/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c02/d00specialnstart.nuanmb
  romfs/fighter/lucas/motion/body/c03/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c03/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c03/d00specialnstart.nuanmb
  romfs/fighter/lucas/motion/body/c04/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c04/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c04/d00specialnstart.nuanmb
  romfs/fighter/lucas/motion/body/c05/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c05/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c05/d00specialnstart.nuanmb
  romfs/fighter/lucas/motion/body/c06/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c06/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c06/d00specialnstart.nuanmb
  romfs/fighter/lucas/motion/body/c07/c05attackairlw.nuanmb
  romfs/fighter/lucas/motion/body/c07/d00specialairnstart.nuanmb
  romfs/fighter/lucas/motion/body/c07/d00specialnstart.nuanmb
  src/lucas/mod.rs
Labels: balance change

#111 Palutena Utilt Changes
  romfs/fighter/palutena/motion/body/c00/c02attackhi3.nuanmb
  romfs/fighter/palutena/motion/body/c01/c02attackhi3.nuanmb
  romfs/fighter/palutena/motion/body/c02/c02attackhi3.nuanmb
  romfs/fighter/palutena/motion/body/c03/c02attackhi3.nuanmb
  romfs/fighter/palutena/motion/body/c04/c02attackhi3.nuanmb
  romfs/fighter/palutena/motion/body/c05/c02attackhi3.nuanmb
  romfs/fighter/palutena/motion/body/c06/c02attackhi3.nuanmb
  romfs/fighter/palutena/motion/body/c07/c02attackhi3.nuanmb
  src/common/faf_change.rs
  src/palutena/mod.rs
Labels: balance change

#112 Sonic Changes
  romfs/config.json
  romfs/fighter/sonic/motion/body/c00/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c00/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c00/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c00/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c00/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c00/motion_list.bin
  romfs/fighter/sonic/motion/body/c01/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c01/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c01/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c01/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c01/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c01/motion_list.bin
  romfs/fighter/sonic/motion/body/c02/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c02/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c02/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c02/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c02/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c02/motion_list.bin
  romfs/fighter/sonic/motion/body/c03/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c03/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c03/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c03/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c03/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c03/motion_list.bin
  romfs/fighter/sonic/motion/body/c04/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c04/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c04/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c04/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c04/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c04/motion_list.bin
  romfs/fighter/sonic/motion/body/c05/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c05/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c05/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c05/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c05/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c05/motion_list.bin
  romfs/fighter/sonic/motion/body/c06/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c06/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c06/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c06/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c06/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c06/motion_list.bin
  romfs/fighter/sonic/motion/body/c07/c04attacklw4.nuanmb
  romfs/fighter/sonic/motion/body/c07/c04attacklw4charge.nuanmb
  romfs/fighter/sonic/motion/body/c07/c05attackairf.nuanmb
  romfs/fighter/sonic/motion/body/c07/c05attackairfhit.nuanmb
  romfs/fighter/sonic/motion/body/c07/c05landingairf.nuanmb
  romfs/fighter/sonic/motion/body/c07/motion_list.bin
  src/sonic/mod.rs
Labels: overhaul, balance change

#129 bowser jr float
  src/koopajr/mod.rs
Labels: overhaul, balance change

#128 GNW dtilt
  romfs/fighter/gamewatch/motion/body/c00/c02attacklw3.nuanmb
  romfs/fighter/gamewatch/motion/body/c01/c02attacklw3.nuanmb
  romfs/fighter/gamewatch/motion/body/c02/c02attacklw3.nuanmb
  romfs/fighter/gamewatch/motion/body/c03/c02attacklw3.nuanmb
  romfs/fighter/gamewatch/motion/body/c04/c02attacklw3.nuanmb
  romfs/fighter/gamewatch/motion/body/c05/c02attacklw3.nuanmb
  romfs/fighter/gamewatch/motion/body/c06/c02attacklw3.nuanmb
  romfs/fighter/gamewatch/motion/body/c07/c02attacklw3.nuanmb
  src/gamewatch/mod.rs
Labels: balance change

#127 Wario Roll Dash Attack
  romfs/fighter/wario/motion/body/c00/c00attackdash.nuanmb
  romfs/fighter/wario/motion/body/c01/c00attackdash.nuanmb
  romfs/fighter/wario/motion/body/c02/c00attackdash.nuanmb
  romfs/fighter/wario/motion/body/c03/c00attackdash.nuanmb
  romfs/fighter/wario/motion/body/c04/c00attackdash.nuanmb
  romfs/fighter/wario/motion/body/c05/c00attackdash.nuanmb
  romfs/fighter/wario/motion/body/c06/c00attackdash.nuanmb
  romfs/fighter/wario/motion/body/c07/c00attackdash.nuanmb
  src/wario/mod.rs
Labels: balance change

#107 Update mod.rs
  romfs/fighter/miigunner/param/vl.prcxml
  src/captain/mod.rs
  src/common/bone.rs
  src/common/cancel.rs
  src/common/command.rs
  src/common/faf_change.rs
  src/miigunner/mod.rs
Labels: balance change
