Repository chrispo-git/ult-s, pull requests merged in 2023-06, with the labels that each got.

#187 Fox Jab 2 Fix
  src/fox/mod.rs
Labels: balance change

#178 Falco Rework
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/falco/motion/body/c00/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c00/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c00/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c00/motion_list.bin
  romfs/fighter/falco/motion/body/c01/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c01/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c01/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c01/motion_list.bin
  romfs/fighter/falco/motion/body/c02/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c02/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c02/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c02/motion_list.bin
  romfs/fighter/falco/motion/body/c03/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c03/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c03/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c03/motion_list.bin
  romfs/fighter/falco/motion/body/c04/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c04/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c04/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c04/motion_list.bin
  romfs/fighter/falco/motion/body/c05/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c05/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c05/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c05/motion_list.bin
  romfs/fighter/falco/motion/body/c06/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c06/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c06/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c06/motion_list.bin
  romfs/fighter/falco/motion/body/c07/c00attackdash.nuanmb
  romfs/fighter/falco/motion/body/c07/c05attackairn.nuanmb
  romfs/fighter/falco/motion/body/c07/c05landingairn.nuanmb
  romfs/fighter/falco/motion/body/c07/motion_list.bin
  src/common/cancel.rs
  src/common/landing.rs
  src/falco/mod.rs
Labels: overhaul, balance change

#175 Daisy Nerfs
  romfs/fighter/common/param/fighter_param.prcxml
  src/daisy/mod.rs
Labels: balance change

#181 Gannondorf
  romfs/fighter/common/param/fighter_param.prcxml
  src/ganon/mod.rs
Labels: balance change

#180 Captain falcon
  src/captain/mod.rs
Labels: balance change

#183 Mythra Buffs
  romfs/fighter/common/param/fighter_param.prcxml
  src/element/mod.rs
Labels: balance change

#184 Motion Input Update
  src/common/command.rs
Labels: enhancement, engine change

#186 Joker Adjustments
  src/common/dacus.rs
  src/jack/mod.rs
Labels: balance change

#176 Wavedash and other adjustments
  src/common/landing.rs
  src/common/wavedash.rs
  src/util/mod.rs
Labels: engine change

#188 Isabelle Jab Buff
  src/shizue/mod.rs
Labels: balance change

#189 Lucina Upb Adjustments
  src/lucina/mod.rs
Labels: balance change

#194 Palutena Adjustments
  romfs/fighter/palutena/motion/body/c00/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c00/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c00/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c00/d03speciallwr.nuanmb
  romfs/fighter/palutena/motion/body/c01/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c01/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c01/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c01/d03speciallwr.nuanmb
  romfs/fighter/palutena/motion/body/c02/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c02/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c02/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c02/d03speciallwr.nuanmb
  romfs/fighter/palutena/motion/body/c03/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c03/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c03/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c03/d03speciallwr.nuanmb
  romfs/fighter/palutena/motion/body/c04/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c04/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c04/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c04/d03speciallwr.nuanmb
  romfs/fighter/palutena/motion/body/c05/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c05/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c05/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c05/d03speciallwr.nuanmb
  romfs/fighter/palutena/motion/body/c06/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c06/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c06/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c06/d03speciallwr.nuanmb
  romfs/fighter/palutena/motion/body/c07/d03specialairlwl.nuanmb
  romfs/fighter/palutena/motion/body/c07/d03specialairlwr.nuanmb
  romfs/fighter/palutena/motion/body/c07/d03speciallwl.nuanmb
  romfs/fighter/palutena/motion/body/c07/d03speciallwr.nuanmb
  romfs/fighter/palutena/param/vl.prcxml
  src/palutena/mod.rs
Labels: balance change

#204 Isabelle Item Pocket Fix
  src/shizue/mod.rs
Labels: bug

#203 Metaknight Dair bugfix
  src/metaknight/mod.rs
Labels: bug

#202 Ryu Copy Ability Bug
  src/ryu/mod.rs
Labels: bug

#199 Kirby Usmash
  romfs/fighter/kirby/motion/body/c00/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c00/c04attackhi4charge.nuanmb
  romfs/fighter/kirby/motion/body/c01/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c01/c04attackhi4charge.nuanmb
  romfs/fighter/kirby/motion/body/c02/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c02/c04attackhi4charge.nuanmb
  romfs/fighter/kirby/motion/body/c03/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c03/c04attackhi4charge.nuanmb
  romfs/fighter/kirby/motion/body/c04/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c04/c04attackhi4charge.nuanmb
  romfs/fighter/kirby/motion/body/c05/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c05/c04attackhi4charge.nuanmb
  romfs/fighter/kirby/motion/body/c06/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c06/c04attackhi4charge.nuanmb
  romfs/fighter/kirby/motion/body/c07/c04attackhi4.nuanmb
  romfs/fighter/kirby/motion/body/c07/c04attackhi4charge.nuanmb
  src/kirby/mod.rs
Labels: balance change

#200 miiswordsman
  src/common/projectile_invuln.rs
  src/miiswordsman/mod.rs
Labels: balance change
