Repository chrispo-git/ult-s, pull requests merged in 2023-05, with the labels that each got.

#169 Jigglypuff Dair adjustment
  src/purin/mod.rs
Labels: balance change

#163 Byleth
  romfs/fighter/common/param/fighter_param.prcxml
  src/common/faf_change.rs
  src/master/mod.rs
Labels: balance change

#165 Mii Gunner Phase 2: Revision
  romfs/fighter/common/param/fighter_param.prcxml
  src/common/faf_change.rs
  src/common/landing.rs
  src/miigunner/mod.rs
Labels: balance change

#167 Zero Suit Samus Adjustments
  romfs/fighter/szerosuit/motion/body/c00/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c00/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c01/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c01/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c02/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c02/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c03/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c03/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c04/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c04/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c05/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c05/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c06/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c06/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c07/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c07/d01specials.nuanmb
  src/szerosuit/mod.rs
Labels: overhaul, balance change

#166 Dark Pit: The Dark Flash
  src/pitb/mod.rs
Labels: balance change

#162 GNW Nerfs
  src/gamewatch/mod.rs
Labels: balance change

#161 Timer UI
  romfs/ui/layout/info/info_melee/info_melee/layout.arc
Labels: enhancement

#164 Sephiroth
  src/common/faf_change.rs
  src/common/landing.rs
  src/edge/mod.rs
Labels: balance change

#159 Sheik changes
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/sheik/motion/body/c00/motion_list.bin
  romfs/fighter/sheik/motion/body/c01/motion_list.bin
  romfs/fighter/sheik/motion/body/c02/motion_list.bin
  romfs/fighter/sheik/motion/body/c03/motion_list.bin
  romfs/fighter/sheik/motion/body/c04/motion_list.bin
  romfs/fighter/sheik/motion/body/c05/motion_list.bin
  romfs/fighter/sheik/motion/body/c06/motion_list.bin
  romfs/fighter/sheik/motion/body/c07/motion_list.bin
  src/sheik/mod.rs
Labels: balance change

#158 Falcon Down B changes
  src/captain/mod.rs
  src/common/landing.rs
Labels: balance change
