Repository chrispo-git/ult-s, pull requests merged in 2023-04, with the labels that each got.

#132 CPU DI
  scripts/build_dev.py
  src/cpu/mod.rs
  src/lib.rs
Labels: enhancement

#150 Mario Nair Adjustment
  src/mario/mod.rs
Labels: balance change

#148 Roy Adjustments
  src/roy/mod.rs
Labels: balance change

#139 Kirby Copy Ability Fix
  romfs/fighter/kirby/motion/body/c00/motion_list.bin
  romfs/fighter/kirby/motion/body/c01/motion_list.bin
  romfs/fighter/kirby/motion/body/c02/motion_list.bin
  romfs/fighter/kirby/motion/body/c03/motion_list.bin
  romfs/fighter/kirby/motion/body/c04/motion_list.bin
  romfs/fighter/kirby/motion/body/c05/motion_list.bin
  romfs/fighter/kirby/motion/body/c06/motion_list.bin
  romfs/fighter/kirby/motion/body/c07/motion_list.bin
  romfs/fighter/kirby/motion/daisybody/c00/daisyd00specialairnhit.nuanmb
  romfs/fighter/kirby/motion/daisybody/c00/daisyd00specialnhit.nuanmb
  romfs/fighter/kirby/motion/masterbody/c00/masterd00specialairn.nuanmb
  romfs/fighter/kirby/motion/masterbody/c00/masterd00specialn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c01/murabitod00specialairn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c01/murabitod00specialn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c02/murabitod00specialairn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c02/murabitod00specialn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c03/murabitod00specialairn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c03/murabitod00specialn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c04/murabitod00specialairn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c04/murabitod00specialn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c05/murabitod00specialairn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c05/murabitod00specialn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c06/murabitod00specialairn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c06/murabitod00specialn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c07/murabitod00specialairn.nuanmb
  romfs/fighter/kirby/motion/murabitobody/c07/murabitod00specialn.nuanmb
  src/daisy/mod.rs
  src/koopa/mod.rs
  src/master/mod.rs
  src/shizue/mod.rs
Labels: bug

#138 Sora Thundaga Fix
  src/trail/mod.rs
Labels: bug

#134 Metaknight Dair
  src/metaknight/mod.rs
Labels: balance change

#133 Duck Hunt Uaftilt Nerf
  src/duckhunt/mod.rs
Labels: balance change

#147 Snake Grenade Item Throw
  romfs/config.json
  romfs/fighter/snake/motion/body/c00/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c00/motion_list.bin
  romfs/fighter/snake/motion/body/c01/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c01/motion_list.bin
  romfs/fighter/snake/motion/body/c02/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c02/motion_list.bin
  romfs/fighter/snake/motion/body/c03/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c03/motion_list.bin
  romfs/fighter/snake/motion/body/c04/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c04/motion_list.bin
  romfs/fighter/snake/motion/body/c05/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c05/motion_list.bin
  romfs/fighter/snake/motion/body/c06/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c06/motion_list.bin
  romfs/fighter/snake/motion/body/c07/c00attackdashlightthrow.nuanmb
  romfs/fighter/snake/motion/body/c07/motion_list.bin
  src/snake/mod.rs
Labels: balance change

#146 Donkey Kong Changes
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/donkey/motion/body/c00/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c00/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c00/motion_list.bin
  romfs/fighter/donkey/motion/body/c01/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c01/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c01/motion_list.bin
  romfs/fighter/donkey/motion/body/c02/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c02/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c02/motion_list.bin
  romfs/fighter/donkey/motion/body/c03/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c03/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c03/motion_list.bin
  romfs/fighter/donkey/motion/body/c04/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c04/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c04/motion_list.bin
  romfs/fighter/donkey/motion/body/c05/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c05/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c05/motion_list.bin
  romfs/fighter/donkey/motion/body/c06/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c06/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c06/motion_list.bin
  romfs/fighter/donkey/motion/body/c07/c05attackairf.nuanmb
  romfs/fighter/donkey/motion/body/c07/e01throwhi.nuanmb
  romfs/fighter/donkey/motion/body/c07/motion_list.bin
  src/common/faf_change.rs
  src/common/landing.rs
  src/donkey/mod.rs
Labels: balance change
