Repository chrispo-git/ult-s, pull requests merged in 2023-11, with the labels that each got.

#334 Wolf Motion list
  romfs/fighter/wolf/motion/body/c00/motion_list.bin
  romfs/fighter/wolf/motion/body/c01/motion_list.bin
  romfs/fighter/wolf/motion/body/c02/motion_list.bin
  romfs/fighter/wolf/motion/body/c03/motion_list.bin
  romfs/fighter/wolf/motion/body/c04/motion_list.bin
  romfs/fighter/wolf/motion/body/c05/motion_list.bin
  romfs/fighter/wolf/motion/body/c06/motion_list.bin
  romfs/fighter/wolf/motion/body/c07/motion_list.bin
  src/common/faf_change.rs
  src/wolf/mod.rs
Labels: enhancement

#347 Daisy Dice Nerf
  romfs/item/daisydaikon/script/animcmd/body/game.lc
Labels: balance change

#346 Wario Proportions fix
  romfs/fighter/wario/motion/body/c00/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c00/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c00/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c00/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c00/c04attacklw4.nuanmb
  romfs/fighter/wario/motion/body/c01/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c01/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c01/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c01/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c01/c04attacklw4.nuanmb
  romfs/fighter/wario/motion/body/c02/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c02/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c02/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c02/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c02/c04attacklw4.nuanmb
  romfs/fighter/wario/motion/body/c03/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c03/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c03/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c03/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c03/c04attacklw4.nuanmb
  romfs/fighter/wario/motion/body/c04/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c04/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c04/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c04/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c04/c04attacklw4.nuanmb
  romfs/fighter/wario/motion/body/c05/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c05/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c05/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c05/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c05/c04attacklw4.nuanmb
  romfs/fighter/wario/motion/body/c06/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c06/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c06/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c06/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c06/c04attacklw4.nuanmb
  romfs/fighter/wario/motion/body/c07/a00wait1.nuanmb
  romfs/fighter/wario/motion/body/c07/c02attackhi3.nuanmb
  romfs/fighter/wario/motion/body/c07/c02attacklw3.nuanmb
  romfs/fighter/wario/motion/body/c07/c03attacks4s.nuanmb
  romfs/fighter/wario/motion/body/c07/c04attacklw4.nuanmb
  src/wario/mod.rs
Labels: aesthetic

#344 Terry Fair changes
  romfs/fighter/dolly/motion/body/c00/motion_list.bin
  romfs/fighter/dolly/motion/body/c01/motion_list.bin
  romfs/fighter/dolly/motion/body/c02/motion_list.bin
  romfs/fighter/dolly/motion/body/c03/motion_list.bin
  romfs/fighter/dolly/motion/body/c04/motion_list.bin
  romfs/fighter/dolly/motion/body/c05/motion_list.bin
  romfs/fighter/dolly/motion/body/c06/motion_list.bin
  romfs/fighter/dolly/motion/body/c07/motion_list.bin
  src/dolly/mod.rs
Labels: balance change

#343 Lucina nerfs
  romfs/fighter/lucina/motion/body/c00/c05attackairf.nuanmb
  romfs/fighter/lucina/motion/body/c01/c05attackairf.nuanmb
  romfs/fighter/lucina/motion/body/c02/c05attackairf.nuanmb
  romfs/fighter/lucina/motion/body/c03/c05attackairf.nuanmb
  romfs/fighter/lucina/motion/body/c04/c05attackairf.nuanmb
  romfs/fighter/lucina/motion/body/c05/c05attackairf.nuanmb
  romfs/fighter/lucina/motion/body/c06/c05attackairf.nuanmb
  romfs/fighter/lucina/motion/body/c07/c05attackairf.nuanmb
  src/lucina/mod.rs
Labels: balance change

#342 Byleth nerfs
  scripts/statistics.py
  src/master/mod.rs
Labels: balance change

#341 Toad Adjustments
  src/murabito/mod.rs
Labels: balance change

#339 Sonic Nair rework
  readme.txt
  romfs/fighter/sonic/motion/body/c00/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c00/c05landingairn.nuanmb
  romfs/fighter/sonic/motion/body/c01/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c01/c05landingairn.nuanmb
  romfs/fighter/sonic/motion/body/c02/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c02/c05landingairn.nuanmb
  romfs/fighter/sonic/motion/body/c03/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c03/c05landingairn.nuanmb
  romfs/fighter/sonic/motion/body/c04/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c04/c05landingairn.nuanmb
  romfs/fighter/sonic/motion/body/c05/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c05/c05landingairn.nuanmb
  romfs/fighter/sonic/motion/body/c06/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c06/c05landingairn.nuanmb
  romfs/fighter/sonic/motion/body/c07/c05attackairn.nuanmb
  romfs/fighter/sonic/motion/body/c07/c05landingairn.nuanmb
  src/sonic/mod.rs
Labels: overhaul

#337 Dark Pit Nair
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/pitb/motion/body/c00/motion_list.bin
  romfs/fighter/pitb/motion/body/c01/motion_list.bin
  romfs/fighter/pitb/motion/body/c02/motion_list.bin
  romfs/fighter/pitb/motion/body/c03/motion_list.bin
  romfs/fighter/pitb/motion/body/c04/motion_list.bin
  romfs/fighter/pitb/motion/body/c05/motion_list.bin
  romfs/fighter/pitb/motion/body/c06/motion_list.bin
  romfs/fighter/pitb/motion/body/c07/motion_list.bin
  src/pitb/mod.rs
Labels: balance change

#336 Mac adjustments
  romfs/fighter/littlemac/motion/body/c00/c00attack11.nuanmb
  romfs/fighter/littlemac/motion/body/c01/c00attack11.nuanmb
  romfs/fighter/littlemac/motion/body/c02/c00attack11.nuanmb
  romfs/fighter/littlemac/motion/body/c03/c00attack11.nuanmb
  romfs/fighter/littlemac/motion/body/c04/c00attack11.nuanmb
  romfs/fighter/littlemac/motion/body/c05/c00attack11.nuanmb
  romfs/fighter/littlemac/motion/body/c06/c00attack11.nuanmb
  romfs/fighter/littlemac/motion/body/c07/c00attack11.nuanmb
  src/littlemac/mod.rs
Labels: balance change

#333 Gunner Clean up
  src/miigunner/mod.rs
Labels: bug
