Repository chrispo-git/ult-s, pull requests merged in 2023-12, with the labels that each got.

#363 Sheik Fthrow fix
  src/murabito/acmd/throws.rs
Labels: bug

#374 Mini Fixes
  readme.txt
  romfs/sound/bank/fighter/se_murabito_c125.nus3audio
  romfs/ui/message/msg_name.msbt
Labels: enhancement

#377 fix
  src/pichu/acmd/aerials.rs
Labels: bug

#376 dsamus nerf
  romfs/fighter/samusd/motion/body/c00/motion_list.bin
  romfs/fighter/samusd/motion/body/c01/motion_list.bin
  romfs/fighter/samusd/motion/body/c02/motion_list.bin
  romfs/fighter/samusd/motion/body/c03/motion_list.bin
  romfs/fighter/samusd/motion/body/c04/motion_list.bin
  romfs/fighter/samusd/motion/body/c05/motion_list.bin
  romfs/fighter/samusd/motion/body/c06/motion_list.bin
  romfs/fighter/samusd/motion/body/c07/motion_list.bin
Labels: balance change

#375 Zerosuit Rework
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/szerosuit/motion/body/c00/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c01/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c02/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c03/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c04/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c05/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c06/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c07/motion_list.bin
  romfs/fighter/szerosuit/param/vl.prcxml
  src/common/cancel.rs
  src/common/dacus.rs
  src/szerosuit/acmd/aerials.rs
  src/szerosuit/acmd/ground.rs
  src/szerosuit/acmd/other.rs
  src/szerosuit/acmd/specials.rs
  src/szerosuit/acmd/throws.rs
  src/szerosuit/acmd/tilts.rs
  src/szerosuit/frame.rs
Labels: balance change

#372 huge param update
  romfs/fighter/common/param/fighter_param.prcxml
Labels: balance change, engine change

#371 Toon link nerfs
  romfs/fighter/toonlink/motion/body/c00/motion_list.bin
  romfs/fighter/toonlink/motion/body/c01/motion_list.bin
  romfs/fighter/toonlink/motion/body/c02/motion_list.bin
  romfs/fighter/toonlink/motion/body/c03/motion_list.bin
  romfs/fighter/toonlink/motion/body/c04/motion_list.bin
  romfs/fighter/toonlink/motion/body/c05/motion_list.bin
  romfs/fighter/toonlink/motion/body/c06/motion_list.bin
  romfs/fighter/toonlink/motion/body/c07/motion_list.bin
  romfs/fighter/toonlink/param/vl.prcxml
  src/toonlink/acmd/aerials.rs
  src/toonlink/acmd/ground.rs
  src/toonlink/acmd/specials.rs
  src/toonlink/acmd/tilts.rs
Labels: balance change

#370 Marth Jab Nerfs
  src/marth/acmd/ground.rs
Labels: balance change

#368 Wolf utilt
  readme.txt
  romfs/fighter/wolf/motion/body/c00/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c00/motion_list.bin
  romfs/fighter/wolf/motion/body/c01/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c01/motion_list.bin
  romfs/fighter/wolf/motion/body/c02/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c02/motion_list.bin
  romfs/fighter/wolf/motion/body/c03/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c03/motion_list.bin
  romfs/fighter/wolf/motion/body/c04/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c04/motion_list.bin
  romfs/fighter/wolf/motion/body/c05/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c05/motion_list.bin
  romfs/fighter/wolf/motion/body/c06/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c06/motion_list.bin
  romfs/fighter/wolf/motion/body/c07/c02attackhi3.nuanmb
  romfs/fighter/wolf/motion/body/c07/motion_list.bin
  src/wolf/acmd/tilts.rs
Labels: balance change

#367 Lucina SM upb nerf
  src/lucina/acmd/specials.rs
Labels: balance change

#366 Simon adjustments
  romfs/config.json
  romfs/fighter/simon/motion/body/c00/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c00/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c00/motion_list.bin
  romfs/fighter/simon/motion/body/c01/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c01/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c01/motion_list.bin
  romfs/fighter/simon/motion/body/c02/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c02/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c02/motion_list.bin
  romfs/fighter/simon/motion/body/c03/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c03/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c03/motion_list.bin
  romfs/fighter/simon/motion/body/c04/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c04/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c04/motion_list.bin
  romfs/fighter/simon/motion/body/c05/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c05/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c05/motion_list.bin
  romfs/fighter/simon/motion/body/c06/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c06/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c06/motion_list.bin
  romfs/fighter/simon/motion/body/c07/c00attackdash.nuanmb
  romfs/fighter/simon/motion/body/c07/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/body/c07/motion_list.bin
  romfs/fighter/simon/motion/whip/c00/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c00/motion_list.bin
  romfs/fighter/simon/motion/whip/c01/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c01/motion_list.bin
  romfs/fighter/simon/motion/whip/c02/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c02/motion_list.bin
  romfs/fighter/simon/motion/whip/c03/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c03/motion_list.bin
  romfs/fighter/simon/motion/whip/c04/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c04/motion_list.bin
  romfs/fighter/simon/motion/whip/c05/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c05/motion_list.bin
  romfs/fighter/simon/motion/whip/c06/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c06/motion_list.bin
  romfs/fighter/simon/motion/whip/c07/c02attacklw3.nuanmb
  romfs/fighter/simon/motion/whip/c07/motion_list.bin
  src/common/faf_change.rs
  src/simon/acmd/ground.rs
  src/simon/acmd/tilts.rs
  src/simon/mod.rs
Labels: overhaul, balance change

#361 Pika nerfs
  romfs/fighter/common/param/fighter_param.prcxml
  src/pikachu/acmd/aerials.rs
  src/pikachu/acmd/tilts.rs
Labels: balance change

#360 Seph nerf
  romfs/fighter/common/param/fighter_param.prcxml
Labels: balance change

#359 Dpit nerf
  romfs/fighter/pitb/motion/body/c00/motion_list.bin
  romfs/fighter/pitb/motion/body/c01/motion_list.bin
  romfs/fighter/pitb/motion/body/c02/motion_list.bin
  romfs/fighter/pitb/motion/body/c03/motion_list.bin
  romfs/fighter/pitb/motion/body/c04/motion_list.bin
  romfs/fighter/pitb/motion/body/c05/motion_list.bin
  romfs/fighter/pitb/motion/body/c06/motion_list.bin
  romfs/fighter/pitb/motion/body/c07/motion_list.bin
Labels: balance change

#358 Falco Changes
  src/falco/acmd/aerials.rs
Labels: balance change

#357 Mii gunner LC fix
  src/miigunner/frame.rs
Labels: bug
