Repository chrispo-git/ult-s, pull requests merged in 2023-10, with the labels that each got.

#241 Ganondorf
  src/ganon/mod.rs
Labels: balance change

#240 Ike
  src/ike/mod.rs
Labels: balance change

#244 Wario
  romfs/fighter/common/param/fighter_param.prcxml
Labels: balance change

#286 Sheik Changes
  romfs/fighter/common/param/fighter_param.prcxml
  src/sheik/mod.rs
Labels: balance change

#271 Lucario, Warrior of Life and Spirit
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/lucario/motion/body/c00/motion_list.bin
  romfs/fighter/lucario/motion/body/c01/motion_list.bin
  romfs/fighter/lucario/motion/body/c02/motion_list.bin
  romfs/fighter/lucario/motion/body/c03/motion_list.bin
  romfs/fighter/lucario/motion/body/c04/motion_list.bin
  romfs/fighter/lucario/motion/body/c05/motion_list.bin
  romfs/fighter/lucario/motion/body/c06/motion_list.bin
  romfs/fighter/lucario/motion/body/c07/motion_list.bin
  src/common/faf_change.rs
  src/lucario/mod.rs
Labels: overhaul, balance change

#300 Build Diff
  scripts/build_diff.py
Labels: tools

#297 Plant Command Input Removal
  src/common/command.rs
Labels: balance change

#296 Mario Command Input removal
  src/common/command.rs
Labels: balance change

#294 Dedede adjustments
  romfs/config.json
  romfs/fighter/dedede/motion/body/c00/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c00/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c00/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c00/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c00/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c00/motion_list.bin
  romfs/fighter/dedede/motion/body/c01/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c01/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c01/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c01/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c01/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c01/motion_list.bin
  romfs/fighter/dedede/motion/body/c02/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c02/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c02/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c02/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c02/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c02/motion_list.bin
  romfs/fighter/dedede/motion/body/c03/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c03/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c03/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c03/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c03/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c03/motion_list.bin
  romfs/fighter/dedede/motion/body/c04/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c04/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c04/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c04/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c04/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c04/motion_list.bin
  romfs/fighter/dedede/motion/body/c05/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c05/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c05/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c05/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c05/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c05/motion_list.bin
  romfs/fighter/dedede/motion/body/c06/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c06/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c06/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c06/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c06/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c06/motion_list.bin
  romfs/fighter/dedede/motion/body/c07/c00attackdash.nuanmb
  romfs/fighter/dedede/motion/body/c07/d00specialairinput.nuanmb
  romfs/fighter/dedede/motion/body/c07/d00specialairinput2.nuanmb
  romfs/fighter/dedede/motion/body/c07/d00specialairinputlanding.nuanmb
  romfs/fighter/dedede/motion/body/c07/d00specialinput.nuanmb
  romfs/fighter/dedede/motion/body/c07/motion_list.bin
  src/common/command.rs
  src/dedede/mod.rs
Labels: balance change

#293 Aegis Adjustments
  src/common/command.rs
  src/element/mod.rs
Labels: balance change

#292 Wii Fit Command Input Removal
  src/common/command.rs
Labels: balance change

#255 Sonic Adjustments
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/sonic/motion/body/c00/motion_list.bin
  romfs/fighter/sonic/motion/body/c01/motion_list.bin
  romfs/fighter/sonic/motion/body/c02/motion_list.bin
  romfs/fighter/sonic/motion/body/c03/motion_list.bin
  romfs/fighter/sonic/motion/body/c04/motion_list.bin
  romfs/fighter/sonic/motion/body/c05/motion_list.bin
  romfs/fighter/sonic/motion/body/c06/motion_list.bin
  romfs/fighter/sonic/motion/body/c07/motion_list.bin
  scripts/char_stats/gamewatch.csv
  src/sonic/mod.rs
Labels: balance change

#272 Fox, Deputy of the Cosmos
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/fox/param/vl.prcxml
  src/fox/mod.rs
Labels: balance change

#268 Palu CI removal
  src/common/command.rs
Labels: balance change

#258 Roy, the Lion of the New Dawn
  src/common/faf_change.rs
  src/roy/mod.rs
Labels: balance change

#245 Byleth, The Fell-Star vessel of the Progenitor God
  romfs/config.json
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/master/motion/body/c00/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c00/motion_list.bin
  romfs/fighter/master/motion/body/c01/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c01/motion_list.bin
  romfs/fighter/master/motion/body/c02/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c02/motion_list.bin
  romfs/fighter/master/motion/body/c03/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c03/motion_list.bin
  romfs/fighter/master/motion/body/c04/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c04/motion_list.bin
  romfs/fighter/master/motion/body/c05/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c05/motion_list.bin
  romfs/fighter/master/motion/body/c06/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c06/motion_list.bin
  romfs/fighter/master/motion/body/c07/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c07/motion_list.bin
  src/master/mod.rs
Labels: balance change

#242 Link, Hero of the Wild that Stops the Kingdom from Crying.
  romfs/config.json
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/link/motion/body/c00/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c00/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c00/motion_list.bin
  romfs/fighter/link/motion/body/c01/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c01/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c01/motion_list.bin
  romfs/fighter/link/motion/body/c02/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c02/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c02/motion_list.bin
  romfs/fighter/link/motion/body/c03/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c03/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c03/motion_list.bin
  romfs/fighter/link/motion/body/c04/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c04/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c04/motion_list.bin
  romfs/fighter/link/motion/body/c05/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c05/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c05/motion_list.bin
  romfs/fighter/link/motion/body/c06/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c06/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c06/motion_list.bin
  romfs/fighter/link/motion/body/c07/c04attacklw4.nuanmb
  romfs/fighter/link/motion/body/c07/c04attacklw4charge.nuanmb
  romfs/fighter/link/motion/body/c07/motion_list.bin
  romfs/fighter/link/motion/bow/c00/c04attacklw4b.nuanmb
  romfs/fighter/link/motion/bow/c01/c04attacklw4b.nuanmb
  romfs/fighter/link/motion/bow/c02/c04attacklw4b.nuanmb
  romfs/fighter/link/motion/bow/c03/c04attacklw4b.nuanmb
  romfs/fighter/link/motion/bow/c04/c04attacklw4b.nuanmb
  romfs/fighter/link/motion/bow/c05/c04attacklw4b.nuanmb
  romfs/fighter/link/motion/bow/c06/c04attacklw4b.nuanmb
  romfs/fighter/link/motion/bow/c07/c04attacklw4b.nuanmb
  src/common/dacus.rs
  src/common/faf_change.rs
  src/link/mod.rs
Labels: balance change

#275 Kirby Ftilt Nerf
  src/kirby/mod.rs
Labels: balance change

#280 Input Buffer Increase
  romfs/fighter/common/param/common.prcxml
Labels: engine change

#283 Ganondorf Nerfs
  romfs/fighter/common/param/fighter_param.prcxml
  src/common/projectile_invuln.rs
  src/ganon/mod.rs
Labels: balance change

#282 Pichu Change
  src/pichu/mod.rs
Labels: balance change

#287 Pit Nerf
  src/pit/mod.rs
Labels: balance change

#289 Parry window revert
  romfs/fighter/common/param/common.prcxml
Labels: engine change

#279 Palutena, the Harbinger of Dawn
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/palutena/motion/body/c00/motion_list.bin
  romfs/fighter/palutena/motion/body/c01/motion_list.bin
  romfs/fighter/palutena/motion/body/c02/motion_list.bin
  romfs/fighter/palutena/motion/body/c03/motion_list.bin
  romfs/fighter/palutena/motion/body/c04/motion_list.bin
  romfs/fighter/palutena/motion/body/c05/motion_list.bin
  romfs/fighter/palutena/motion/body/c06/motion_list.bin
  romfs/fighter/palutena/motion/body/c07/motion_list.bin
  romfs/fighter/palutena/param/vl.prcxml
  src/common/command.rs
  src/common/faf_change.rs
  src/palutena/mod.rs
Labels: balance change

#284 Chrom Changes
  romfs/fighter/chrom/motion/body/c00/motion_list.bin
  romfs/fighter/chrom/motion/body/c01/motion_list.bin
  romfs/fighter/chrom/motion/body/c02/motion_list.bin
  romfs/fighter/chrom/motion/body/c03/motion_list.bin
  romfs/fighter/chrom/motion/body/c04/motion_list.bin
  romfs/fighter/chrom/motion/body/c05/motion_list.bin
  romfs/fighter/chrom/motion/body/c06/motion_list.bin
  romfs/fighter/chrom/motion/body/c07/motion_list.bin
  romfs/fighter/common/param/fighter_param.prcxml
  src/chrom/mod.rs
Labels: balance change

#288 Dark Pit Movement Buff
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/pitb/motion/body/c00/motion_list.bin
  romfs/fighter/pitb/motion/body/c01/motion_list.bin
  romfs/fighter/pitb/motion/body/c02/motion_list.bin
  romfs/fighter/pitb/motion/body/c03/motion_list.bin
  romfs/fighter/pitb/motion/body/c04/motion_list.bin
  romfs/fighter/pitb/motion/body/c05/motion_list.bin
  romfs/fighter/pitb/motion/body/c06/motion_list.bin
  romfs/fighter/pitb/motion/body/c07/motion_list.bin
  romfs/fighter/pitb/param/vl.prcxml
  src/pitb/mod.rs
Labels: balance change

#256 Terry Bogard, heir to the Bogard Zaibatsu
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/dolly/motion/body/c00/motion_list.bin
  romfs/fighter/dolly/motion/body/c01/motion_list.bin
  romfs/fighter/dolly/motion/body/c02/motion_list.bin
  romfs/fighter/dolly/motion/body/c03/motion_list.bin
  romfs/fighter/dolly/motion/body/c04/motion_list.bin
  romfs/fighter/dolly/motion/body/c05/motion_list.bin
  romfs/fighter/dolly/motion/body/c06/motion_list.bin
  romfs/fighter/dolly/motion/body/c07/motion_list.bin
  src/common/command.rs
  src/common/faf_change.rs
  src/dolly/mod.rs
Labels: balance change

#273 The Hero, Bravery Incarnate
  romfs/fighter/brave/motion/body/c00/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c00/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c00/motion_list.bin
  romfs/fighter/brave/motion/body/c01/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c01/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c01/motion_list.bin
  romfs/fighter/brave/motion/body/c02/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c02/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c02/motion_list.bin
  romfs/fighter/brave/motion/body/c03/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c03/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c03/motion_list.bin
  romfs/fighter/brave/motion/body/c04/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c04/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c04/motion_list.bin
  romfs/fighter/brave/motion/body/c05/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c05/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c05/motion_list.bin
  romfs/fighter/brave/motion/body/c06/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c06/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c06/motion_list.bin
  romfs/fighter/brave/motion/body/c07/d02specialhi1.nuanmb
  romfs/fighter/brave/motion/body/c07/d02specialhifailure.nuanmb
  romfs/fighter/brave/motion/body/c07/motion_list.bin
  romfs/fighter/brave/param/vl.prc
  romfs/fighter/common/param/fighter_param.prcxml
  src/brave/mod.rs
  src/common/faf_change.rs
Labels: balance change

#304 Fix Emulator latency
  src/lib.rs
Labels: bug

#307 Dark Pit gravity fix
  romfs/fighter/common/param/fighter_param.prcxml
Labels: balance change

#325 Mii Swordfighter Rework
  romfs/config.json
  romfs/fighter/miiswordsman/motion/body/c00/c01attacks3hi.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/c01attacks3lw.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/c01attacks3s.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/c03attacks4s.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/c04attackhi4.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/c04attackhi4charge.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/d00specialairn2.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/d00specialn2.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/d01specials1.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/d01specials1hit.nuanmb
  romfs/fighter/miiswordsman/motion/body/c00/motion_list.bin
  romfs/fighter/miiswordsman/param/vl.prc
  romfs/fighter/miiswordsman/param/vl.prcxml
  src/common/faf_change.rs
  src/miiswordsman/mod.rs
Labels: overhaul

#323 Sonic Sideb Rework
  romfs/fighter/sonic/motion/body/c00/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c00/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c00/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c00/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c00/motion_list.bin
  romfs/fighter/sonic/motion/body/c01/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c01/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c01/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c01/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c01/motion_list.bin
  romfs/fighter/sonic/motion/body/c02/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c02/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c02/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c02/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c02/motion_list.bin
  romfs/fighter/sonic/motion/body/c03/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c03/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c03/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c03/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c03/motion_list.bin
  romfs/fighter/sonic/motion/body/c04/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c04/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c04/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c04/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c04/motion_list.bin
  romfs/fighter/sonic/motion/body/c05/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c05/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c05/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c05/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c05/motion_list.bin
  romfs/fighter/sonic/motion/body/c06/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c06/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c06/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c06/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c06/motion_list.bin
  romfs/fighter/sonic/motion/body/c07/c05attackairlw.nuanmb
  romfs/fighter/sonic/motion/body/c07/d01specialairsstart.nuanmb
  romfs/fighter/sonic/motion/body/c07/d01specialsstart.nuanmb
  romfs/fighter/sonic/motion/body/c07/j01appeallwr.nuanmb
  romfs/fighter/sonic/motion/body/c07/motion_list.bin
  scripts/build_dev.py
  src/sonic/mod.rs
  src/util/mod.rs
Labels: overhaul, balance change
