Repository chrispo-git/ult-s, pull requests merged in 2024-07, with the labels that each got.

#471 Rayman Fsmash nerfs
  romfs/fighter/pikmin/motion/body/c120/motion_list.bin
  src/rayman/acmd/ground.rs
Labels: balance change

#472 Sandbag Neutralb nerf
  src/sandbag/acmd/specials.rs
Labels: balance change

#473 Rayman vc probability
  src/rayman/acmd/specials.rs
  src/rayman/mod.rs
Labels: aesthetic

#476 Kirby Fixes
  changelog/kirby.md
  src/kirby/acmd/specials.rs
  src/kirby/status.rs
Labels: bug

#482 Masked Man Dthrow Nerf
  changelog/masked.md
  src/masked/acmd/throws.rs
Labels: balance change

#483 Mii Brawler nerfs
  changelog/brawler.md
  src/common/projectile_invuln.rs
  src/miifighter/acmd/aerials.rs
  src/miifighter/acmd/specials.rs
Labels: balance change

#484 Falcon Usmash Nerf
  changelog/falcon.md
  src/captain/acmd/ground.rs
  src/common/command.rs
Labels: balance change

#485 Mii Gunner Nerfs
  romfs/fighter/common/param/fighter_param.prcxml
  src/common/cancel.rs
  src/miigunner/acmd/ground.rs
  src/miigunner/acmd/other.rs
  src/miigunner/acmd/specials.rs
  src/miigunner/acmd/tilts.rs
  src/miigunner/frame.rs
Labels: balance change

#486 Projectile Invuln Removal Sweep
  src/common/projectile_invuln.rs
Labels: balance change

#487 DK Nerfs
  src/donkey/acmd/specials.rs
  src/donkey/acmd/tilts.rs
Labels: balance change

#489 Dpit Rework
  romfs/fighter/common/param/fighter_param.prcxml
  src/pitb/acmd/aerials.rs
  src/pitb/frame.rs
Labels: balance change

#491 Tink adjustments
  changelog/toonlink.md
  romfs/fighter/link/motion/body/c01/motion_list.bin
  romfs/fighter/link/motion/body/c02/motion_list.bin
  romfs/fighter/link/motion/body/c03/motion_list.bin
  romfs/fighter/link/motion/body/c04/motion_list.bin
  romfs/fighter/link/motion/body/c05/motion_list.bin
  romfs/fighter/link/motion/body/c06/motion_list.bin
  romfs/fighter/link/motion/body/c07/motion_list.bin
  romfs/fighter/toonlink/motion/body/c00/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c00/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c00/motion_list.bin
  romfs/fighter/toonlink/motion/body/c01/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c01/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c01/motion_list.bin
  romfs/fighter/toonlink/motion/body/c02/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c02/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c02/motion_list.bin
  romfs/fighter/toonlink/motion/body/c03/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c03/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c03/motion_list.bin
  romfs/fighter/toonlink/motion/body/c04/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c04/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c04/motion_list.bin
  romfs/fighter/toonlink/motion/body/c05/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c05/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c05/motion_list.bin
  romfs/fighter/toonlink/motion/body/c06/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c06/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c06/motion_list.bin
  romfs/fighter/toonlink/motion/body/c07/c04attackhi4.nuanmb
  romfs/fighter/toonlink/motion/body/c07/c04attackhi4charge.nuanmb
  romfs/fighter/toonlink/motion/body/c07/motion_list.bin
  src/common/mod.rs
  src/lib.rs
  src/toonlink/acmd/ground.rs
  src/toonlink/acmd/specials.rs
  src/toonlink/frame.rs
  src/toonlink/mod.rs
  src/toonlink/status.rs
Labels: balance change

#490 Training mode fixes
  src/common/mod.rs
  src/common/training.rs
  src/util/mod.rs
Labels: enhancement
