Repository chrispo-git/ult-s, pull requests merged in 2024-04, with the labels that each got.

#432 Bayonetta taunt restore
  romfs/fighter/bayonetta/motion/body/c00/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c00/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c00/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c00/j01appealsr.nuanmb
  romfs/fighter/bayonetta/motion/body/c01/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c01/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c01/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c01/j01appealsr.nuanmb
  romfs/fighter/bayonetta/motion/body/c02/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c02/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c02/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c02/j01appealsr.nuanmb
  romfs/fighter/bayonetta/motion/body/c03/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c03/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c03/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c03/j01appealsr.nuanmb
  romfs/fighter/bayonetta/motion/body/c04/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c04/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c04/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c04/j01appealsr.nuanmb
  romfs/fighter/bayonetta/motion/body/c05/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c05/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c05/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c05/j01appealsr.nuanmb
  romfs/fighter/bayonetta/motion/body/c06/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c06/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c06/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c06/j01appealsr.nuanmb
  romfs/fighter/bayonetta/motion/body/c07/j01appealhil.nuanmb
  romfs/fighter/bayonetta/motion/body/c07/j01appealhir.nuanmb
  romfs/fighter/bayonetta/motion/body/c07/j01appeallwr.nuanmb
  romfs/fighter/bayonetta/motion/body/c07/j01appealsr.nuanmb
Labels: aesthetic

#435 Mii Brawler Shotput buff
  changelog/brawler.md
  romfs/fighter/miifighter/motion/body/c00/motion_list.bin
Labels: balance change

#445 Dark Pit Expressions Fix
  romfs/fighter/pitb/motion/body/c00/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c00/c05attackairn.nuanmb
  romfs/fighter/pitb/motion/body/c01/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c01/c05attackairn.nuanmb
  romfs/fighter/pitb/motion/body/c02/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c02/c05attackairn.nuanmb
  romfs/fighter/pitb/motion/body/c03/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c03/c05attackairn.nuanmb
  romfs/fighter/pitb/motion/body/c04/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c04/c05attackairn.nuanmb
  romfs/fighter/pitb/motion/body/c05/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c05/c05attackairn.nuanmb
  romfs/fighter/pitb/motion/body/c06/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c06/c05attackairn.nuanmb
  romfs/fighter/pitb/motion/body/c07/c05attackairhi.nuanmb
  romfs/fighter/pitb/motion/body/c07/c05attackairn.nuanmb
Labels: aesthetic

#441 Doc Aesthetics update
  romfs/fighter/mariod/motion/body/c00/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c00/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c00/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c00/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c00/j01appeallwr.nuanmb
  romfs/fighter/mariod/motion/body/c01/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c01/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c01/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c01/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c01/j01appeallwr.nuanmb
  romfs/fighter/mariod/motion/body/c02/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c02/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c02/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c02/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c02/j01appeallwr.nuanmb
  romfs/fighter/mariod/motion/body/c03/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c03/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c03/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c03/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c03/j01appeallwr.nuanmb
  romfs/fighter/mariod/motion/body/c04/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c04/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c04/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c04/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c04/j01appeallwr.nuanmb
  romfs/fighter/mariod/motion/body/c05/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c05/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c05/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c05/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c05/j01appeallwr.nuanmb
  romfs/fighter/mariod/motion/body/c06/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c06/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c06/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c06/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c06/j01appeallwr.nuanmb
  romfs/fighter/mariod/motion/body/c07/a00wait2.nuanmb
  romfs/fighter/mariod/motion/body/c07/a00wait3.nuanmb
  romfs/fighter/mariod/motion/body/c07/c05attackairf.nuanmb
  romfs/fighter/mariod/motion/body/c07/j01appealhir.nuanmb
  romfs/fighter/mariod/motion/body/c07/j01appeallwr.nuanmb
Labels: aesthetic

#443 Bowser nerfs
  changelog/bowser.md
  src/koopa/acmd/ground.rs
  src/koopa/acmd/specials.rs
Labels: balance change

#442 Corrin Jab Nerf
  src/kamui/acmd/ground.rs
Labels: balance change

#438 Training Mode Changes
  src/common/mod.rs
  src/common/training.rs
  src/cpu/mod.rs
  src/util/mod.rs
Labels: enhancement
