Repository chrispo-git/ult-s, pull requests merged in 2024-02, with the labels that each got.

#419 Knockdown throws
  src/common/hitstun.rs
  src/common/wavedash.rs
  src/util/mod.rs
Labels: enhancement

#422 13.0.2 offset fix
  src/controls/controls_2.rs
  src/controls/mod.rs
  src/lib.rs
Labels: engine change

#424 Fix Statistics.py and add stats2md.py
  .gitignore
  scripts/statistics.py
  scripts/stats2md.py
Labels: enhancement

#425 Data Doc Pt.1
  changelog/daisy.md
  changelog/drmario.md
  changelog/fox.md
  changelog/how2changelog.md
  changelog/isabelle.md
  changelog/jigglypuff.md
  changelog/kirby.md
  changelog/link.md
  changelog/mario.md
  changelog/marth.md
  changelog/pikachu.md
  changelog/roy.md
  changelog/sonic.md
  scripts/statistics.py
  scripts/stats2md.py
Labels: changelog

#426 Data doc extend
  changelog/bowser.md
  changelog/falcon.md
  changelog/how2changelog.md
  changelog/ike.md
  changelog/metaknight.md
  changelog/wiifit.md
  romfs/fighter/ike/motion/body/c00/motion_list.bin
  romfs/fighter/ike/motion/body/c01/motion_list.bin
  romfs/fighter/ike/motion/body/c02/motion_list.bin
  romfs/fighter/ike/motion/body/c03/motion_list.bin
  romfs/fighter/ike/motion/body/c04/motion_list.bin
  romfs/fighter/ike/motion/body/c05/motion_list.bin
  romfs/fighter/ike/motion/body/c06/motion_list.bin
  romfs/fighter/ike/motion/body/c07/motion_list.bin
  romfs/fighter/wiifit/motion/body/c00/motion_list.bin
  romfs/fighter/wiifit/motion/body/c01/motion_list.bin
  romfs/fighter/wiifit/motion/body/c02/motion_list.bin
  romfs/fighter/wiifit/motion/body/c03/motion_list.bin
  romfs/fighter/wiifit/motion/body/c04/motion_list.bin
  romfs/fighter/wiifit/motion/body/c05/motion_list.bin
  romfs/fighter/wiifit/motion/body/c06/motion_list.bin
  romfs/fighter/wiifit/motion/body/c07/motion_list.bin
Labels: changelog

#428 Daisy adjustments
  changelog/daisy.md
  romfs/fighter/daisy/motion/body/c00/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c00/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c00/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c01/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c01/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c01/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c02/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c02/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c02/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c03/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c03/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c03/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c04/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c04/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c04/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c05/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c05/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c05/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c06/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c06/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c06/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c07/c01attacks3s.nuanmb
  romfs/fighter/daisy/motion/body/c07/c05attackairf.nuanmb
  romfs/fighter/daisy/motion/body/c07/swingblend.prcxml
  src/daisy/acmd/aerials.rs
  src/daisy/acmd/tilts.rs
Labels: balance change, aesthetic

#423 Chrom ftilt
  changelog/chrom.md
  romfs/fighter/chrom/motion/body/c00/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c00/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c00/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c00/motion_list.bin
  romfs/fighter/chrom/motion/body/c01/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c01/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c01/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c01/motion_list.bin
  romfs/fighter/chrom/motion/body/c02/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c02/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c02/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c02/motion_list.bin
  romfs/fighter/chrom/motion/body/c03/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c03/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c03/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c03/motion_list.bin
  romfs/fighter/chrom/motion/body/c04/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c04/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c04/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c04/motion_list.bin
  romfs/fighter/chrom/motion/body/c05/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c05/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c05/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c05/motion_list.bin
  romfs/fighter/chrom/motion/body/c06/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c06/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c06/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c06/motion_list.bin
  romfs/fighter/chrom/motion/body/c07/c01attacks3hi.nuanmb
  romfs/fighter/chrom/motion/body/c07/c01attacks3lw.nuanmb
  romfs/fighter/chrom/motion/body/c07/c01attacks3s.nuanmb
  romfs/fighter/chrom/motion/body/c07/motion_list.bin
  src/chrom/acmd/specials.rs
  src/chrom/acmd/tilts.rs
  src/chrom/frame.rs
Labels: balance change, aesthetic

#421 Lucario SFX + sideb rework
  changelog/lucario.md
  romfs/fighter/lucario/motion/body/c00/motion_list.bin
  romfs/fighter/lucario/motion/body/c01/motion_list.bin
  romfs/fighter/lucario/motion/body/c02/motion_list.bin
  romfs/fighter/lucario/motion/body/c03/motion_list.bin
  romfs/fighter/lucario/motion/body/c04/motion_list.bin
  romfs/fighter/lucario/motion/body/c05/motion_list.bin
  romfs/fighter/lucario/motion/body/c06/motion_list.bin
  romfs/fighter/lucario/motion/body/c07/motion_list.bin
  romfs/fighter/pikmin/model/body/c121/def_pikmin_001_col.nutexb
  src/lucario/acmd/aerials.rs
  src/lucario/acmd/ground.rs
  src/lucario/acmd/specials.rs
  src/lucario/acmd/tilts.rs
Labels: balance change

#420 Bowser Jr knockdown Throw
  src/koopajr/acmd/throws.rs
Labels: balance change

#418 Richter knife rework
  romfs/fighter/richter/param/vl.prcxml
  src/richter/acmd/specials.rs
  src/richter/frame.rs
  src/richter/mod.rs
Labels: balance change

#417 Zelda Din's Adjustment
  romfs/fighter/zelda/motion/body/c00/motion_list.bin
  romfs/fighter/zelda/motion/body/c01/motion_list.bin
  romfs/fighter/zelda/motion/body/c02/motion_list.bin
  romfs/fighter/zelda/motion/body/c03/motion_list.bin
  romfs/fighter/zelda/motion/body/c04/motion_list.bin
  romfs/fighter/zelda/motion/body/c05/motion_list.bin
  romfs/fighter/zelda/motion/body/c06/motion_list.bin
  romfs/fighter/zelda/motion/body/c07/motion_list.bin
  src/zelda/frame.rs
Labels: balance change

#416 Snake Grab walking removal
  src/snake/status.rs
Labels: balance change

#414 Hero Tweaks
  src/brave/acmd/tilts.rs
  src/common/projectile_invuln.rs
Labels: balance change

#413 Robin tweaks
  src/reflet/acmd/aerials.rs
  src/reflet/acmd/specials.rs
Labels: balance change

#412 Incineroar, Symbol of Power and Fury
  romfs/fighter/gaogaen/motion/body/c00/motion_list.bin
  romfs/fighter/gaogaen/motion/body/c01/motion_list.bin
  romfs/fighter/gaogaen/motion/body/c02/motion_list.bin
  romfs/fighter/gaogaen/motion/body/c03/motion_list.bin
  romfs/fighter/gaogaen/motion/body/c04/motion_list.bin
  romfs/fighter/gaogaen/motion/body/c05/motion_list.bin
  romfs/fighter/gaogaen/motion/body/c06/motion_list.bin
  romfs/fighter/gaogaen/motion/body/c07/motion_list.bin
  src/gaogaen/acmd/specials.rs
  src/gaogaen/acmd/tilts.rs
Labels: balance change

#411 Kirby Ftilt Reversion
  romfs/fighter/kirby/motion/body/c00/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c00/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c00/c01attacks3s.nuanmb
  romfs/fighter/kirby/motion/body/c01/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c01/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c01/c01attacks3s.nuanmb
  romfs/fighter/kirby/motion/body/c02/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c02/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c02/c01attacks3s.nuanmb
  romfs/fighter/kirby/motion/body/c03/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c03/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c03/c01attacks3s.nuanmb
  romfs/fighter/kirby/motion/body/c04/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c04/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c04/c01attacks3s.nuanmb
  romfs/fighter/kirby/motion/body/c05/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c05/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c05/c01attacks3s.nuanmb
  romfs/fighter/kirby/motion/body/c06/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c06/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c06/c01attacks3s.nuanmb
  romfs/fighter/kirby/motion/body/c07/c01attacks3hi.nuanmb
  romfs/fighter/kirby/motion/body/c07/c01attacks3lw.nuanmb
  romfs/fighter/kirby/motion/body/c07/c01attacks3s.nuanmb
  src/kirby/acmd/tilts.rs
Labels: balance change

#410 Metaknight Multihit Tornado
  src/metaknight/acmd/specials.rs
Labels: balance change

#409 Dark Samus Zair
  romfs/fighter/common/param/fighter_param.prcxml
Labels: balance change

#406 Marth nerfs
  changelog/marth.md
  romfs/fighter/marth/motion/body/c00/motion_list.bin
  romfs/fighter/marth/motion/body/c01/motion_list.bin
  romfs/fighter/marth/motion/body/c02/motion_list.bin
  romfs/fighter/marth/motion/body/c03/motion_list.bin
  romfs/fighter/marth/motion/body/c04/motion_list.bin
  romfs/fighter/marth/motion/body/c05/motion_list.bin
  romfs/fighter/marth/motion/body/c06/motion_list.bin
  romfs/fighter/marth/motion/body/c07/motion_list.bin
  src/marth/acmd/ground.rs
  src/marth/acmd/specials.rs
Labels: balance change

#405 Villager Neutral Special Bugfix
  src/murabito/frame.rs
  src/murabito/status.rs
Labels: bug

#404 Sonic homing attack on hit
  romfs/fighter/sonic/param/vl.prcxml
Labels: balance change

#398 Ganondorf, great king of mix
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/ganon/motion/body/c00/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c00/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c00/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c00/motion_list.bin
  romfs/fighter/ganon/motion/body/c01/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c01/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c01/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c01/motion_list.bin
  romfs/fighter/ganon/motion/body/c02/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c02/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c02/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c02/motion_list.bin
  romfs/fighter/ganon/motion/body/c03/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c03/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c03/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c03/motion_list.bin
  romfs/fighter/ganon/motion/body/c04/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c04/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c04/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c04/motion_list.bin
  romfs/fighter/ganon/motion/body/c05/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c05/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c05/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c05/motion_list.bin
  romfs/fighter/ganon/motion/body/c06/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c06/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c06/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c06/motion_list.bin
  romfs/fighter/ganon/motion/body/c07/e01throwb.nuanmb
  romfs/fighter/ganon/motion/body/c07/e01throwf.nuanmb
  romfs/fighter/ganon/motion/body/c07/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c07/motion_list.bin
  src/ganon/acmd/aerials.rs
  src/ganon/acmd/specials.rs
  src/ganon/acmd/throws.rs
  src/ganon/frame.rs
Labels: balance change
