Repository chrispo-git/ult-s, pull requests merged in 2024-08, with the labels that each got.

#501 Daisy Minor Rework
  changelog/daisy.md
  romfs/fighter/daisy/motion/body/c00/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c00/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c00/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c00/motion_list.bin
  romfs/fighter/daisy/motion/body/c00/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c01/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c01/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c01/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c01/motion_list.bin
  romfs/fighter/daisy/motion/body/c01/swingblend.prc
  romfs/fighter/daisy/motion/body/c01/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c02/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c02/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c02/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c02/motion_list.bin
  romfs/fighter/daisy/motion/body/c02/swingblend.prc
  romfs/fighter/daisy/motion/body/c02/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c03/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c03/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c03/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c03/motion_list.bin
  romfs/fighter/daisy/motion/body/c03/swingblend.prc
  romfs/fighter/daisy/motion/body/c03/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c04/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c04/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c04/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c04/motion_list.bin
  romfs/fighter/daisy/motion/body/c04/swingblend.prc
  romfs/fighter/daisy/motion/body/c04/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c05/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c05/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c05/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c05/motion_list.bin
  romfs/fighter/daisy/motion/body/c05/swingblend.prc
  romfs/fighter/daisy/motion/body/c05/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c06/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c06/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c06/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c06/motion_list.bin
  romfs/fighter/daisy/motion/body/c06/swingblend.prc
  romfs/fighter/daisy/motion/body/c06/swingblend.prcxml
  romfs/fighter/daisy/motion/body/c07/c00attack12.nuanmb
  romfs/fighter/daisy/motion/body/c07/c02attacklw3.nuanmb
  romfs/fighter/daisy/motion/body/c07/c04attackhi4.nuanmb
  romfs/fighter/daisy/motion/body/c07/motion_list.bin
  romfs/fighter/daisy/motion/body/c07/swingblend.prc
  romfs/fighter/daisy/motion/body/c07/swingblend.prcxml
  src/daisy/acmd/ground.rs
  src/daisy/acmd/specials.rs
  src/daisy/acmd/throws.rs
  src/daisy/acmd/tilts.rs
  src/daisy/status.rs
Labels: overhaul, balance change

#500 Palutena Fair adjustment
  src/palutena/acmd/aerials.rs
Labels: balance change

#493 Zero Suit Rework
  changelog/zerosuit.md
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/szerosuit/motion/body/c00/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c00/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c00/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c00/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c01/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c01/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c01/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c01/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c02/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c02/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c02/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c02/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c03/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c03/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c03/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c03/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c04/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c04/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c04/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c04/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c05/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c05/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c05/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c05/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c06/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c06/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c06/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c06/motion_list.bin
  romfs/fighter/szerosuit/motion/body/c07/c00attackdash.nuanmb
  romfs/fighter/szerosuit/motion/body/c07/d01specialairs.nuanmb
  romfs/fighter/szerosuit/motion/body/c07/d01specials.nuanmb
  romfs/fighter/szerosuit/motion/body/c07/motion_list.bin
  scripts/build_char.py
  src/common/wavedash.rs
  src/szerosuit/acmd/aerials.rs
  src/szerosuit/acmd/ground.rs
  src/szerosuit/acmd/specials.rs
  src/szerosuit/acmd/throws.rs
  src/szerosuit/acmd/tilts.rs
  src/szerosuit/frame.rs
Labels: overhaul, balance change

#492 Remove All Command Inputs
  src/common/command.rs
  src/common/mod.rs
Labels: enhancement

#494 Pacman Butt Bounce
  changelog/pacman.md
  romfs/fighter/pacman/motion/body/c00/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c00/motion_list.bin
  romfs/fighter/pacman/motion/body/c01/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c01/motion_list.bin
  romfs/fighter/pacman/motion/body/c02/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c02/motion_list.bin
  romfs/fighter/pacman/motion/body/c03/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c03/motion_list.bin
  romfs/fighter/pacman/motion/body/c04/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c04/motion_list.bin
  romfs/fighter/pacman/motion/body/c05/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c05/motion_list.bin
  romfs/fighter/pacman/motion/body/c06/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c06/motion_list.bin
  romfs/fighter/pacman/motion/body/c07/d03specialairlwfailure.nuanmb
  romfs/fighter/pacman/motion/body/c07/motion_list.bin
  romfs/fighter/pacman/param/vl.prcxml
  src/pacman/acmd/specials.rs
  src/pacman/frame.rs
Labels: overhaul

#495 Byleth Adjustments
  romfs/fighter/master/motion/body/c00/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c00/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c00/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c00/d01specialsf.nuanmb
  romfs/fighter/master/motion/body/c01/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c01/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c01/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c01/d01specialsf.nuanmb
  romfs/fighter/master/motion/body/c02/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c02/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c02/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c02/d01specialsf.nuanmb
  romfs/fighter/master/motion/body/c03/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c03/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c03/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c03/d01specialsf.nuanmb
  romfs/fighter/master/motion/body/c04/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c04/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c04/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c04/d01specialsf.nuanmb
  romfs/fighter/master/motion/body/c05/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c05/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c05/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c05/d01specialsf.nuanmb
  romfs/fighter/master/motion/body/c06/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c06/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c06/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c06/d01specialsf.nuanmb
  romfs/fighter/master/motion/body/c07/c05attackairn.nuanmb
  romfs/fighter/master/motion/body/c07/d01specialairsf.nuanmb
  romfs/fighter/master/motion/body/c07/d01specialairsstart.nuanmb
  romfs/fighter/master/motion/body/c07/d01specialsf.nuanmb
  src/master/acmd/aerials.rs
  src/master/acmd/specials.rs
Labels: balance change

#496 Dedede Gordo change
  src/dedede/acmd/specials.rs
  src/dedede/frame.rs
  src/dedede/mod.rs
Labels: balance change

#497 Hero Ftilt reversion
  src/brave/frame.rs
Labels: balance change
