Repository chrispo-git/ult-s, pull requests merged in 2024-12, with the labels that each got.

#544 Brawler Dair angle change
  romfs/fighter/miifighter/motion/body/c00/c05attackairlw.nuanmb
  romfs/fighter/miifighter/motion/body/c00/c05attackairlwbounce.nuanmb
  src/miifighter/acmd/aerials.rs
Labels: balance change, aesthetic

#540 Fix controls menu
  src/controls/controls_2.rs
Labels: bug

#535 Bomberman flash
  src/bomberman/status.rs
Labels: aesthetic
