Repository chrispo-git/ult-s, pull requests merged in 2024-01, with the labels that each got.

#391 Removing SH button macro
  romfs/ui/message/msg_menu.xmsbt
  src/util/mod.rs
Labels: bug

#395 Dark samus sideb bugfix
  src/samusd/acmd/specials.rs
  src/samusd/frame.rs
Labels: bug

#394 Mario adjustments
  src/mario/acmd/aerials.rs
Labels: balance change

#393 Mii Gunner Nerfs
  romfs/fighter/common/param/fighter_param.prcxml
  romfs/fighter/miigunner/motion/body/c00/d02specialairhi1.nuanmb
  romfs/fighter/miigunner/motion/body/c00/d02specialhi1.nuanmb
  src/miigunner/acmd/aerials.rs
  src/miigunner/acmd/ground.rs
  src/miigunner/acmd/specials.rs
  src/miigunner/frame.rs
  src/miigunner/mod.rs
Labels: balance change

#392 Wario adjustments
  romfs/fighter/wario/motion/body/c00/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c00/d01specialssearch.nuanmb
  romfs/fighter/wario/motion/body/c01/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c01/d01specialssearch.nuanmb
  romfs/fighter/wario/motion/body/c02/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c02/d01specialssearch.nuanmb
  romfs/fighter/wario/motion/body/c03/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c03/d01specialssearch.nuanmb
  romfs/fighter/wario/motion/body/c04/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c04/d01specialssearch.nuanmb
  romfs/fighter/wario/motion/body/c05/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c05/d01specialssearch.nuanmb
  romfs/fighter/wario/motion/body/c06/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c06/d01specialssearch.nuanmb
  romfs/fighter/wario/motion/body/c07/d01specialairssearch.nuanmb
  romfs/fighter/wario/motion/body/c07/d01specialssearch.nuanmb
  romfs/fighter/wario/param/vl.prcxml
  src/wario/acmd/specials.rs
  src/wario/frame.rs
Labels: balance change

#390 Duck Hunt Nerfs
  src/duckhunt/acmd/aerials.rs
  src/duckhunt/acmd/tilts.rs
Labels: balance change

#388 Jigglypuff nerfs
  romfs/fighter/common/param/fighter_param.prcxml
  src/purin/acmd/ground.rs
Labels: balance change

#386 Dsamus buff
  romfs/fighter/common/param/fighter_param_motion.prcxml
  romfs/fighter/samusd/motion/body/c00/motion_list.bin
  romfs/fighter/samusd/motion/body/c01/motion_list.bin
  romfs/fighter/samusd/motion/body/c02/motion_list.bin
  romfs/fighter/samusd/motion/body/c03/motion_list.bin
  romfs/fighter/samusd/motion/body/c04/motion_list.bin
  romfs/fighter/samusd/motion/body/c05/motion_list.bin
  romfs/fighter/samusd/motion/body/c06/motion_list.bin
  romfs/fighter/samusd/motion/body/c07/motion_list.bin
  romfs/fighter/samusd/param/vl.prcxml
  src/samusd/acmd/tilts.rs
  src/samusd/frame.rs
Labels: balance change

#385 Chrom Sideb and daftilt buffs
  src/chrom/acmd/specials.rs
  src/chrom/acmd/tilts.rs
  src/chrom/frame.rs
Labels: balance change

#384 GNW Dair spike
  src/gamewatch/acmd/aerials.rs
Labels: balance change

#383 luigi buff
  romfs/fighter/luigi/motion/body/c00/motion_list.bin
  romfs/fighter/luigi/motion/body/c01/motion_list.bin
  romfs/fighter/luigi/motion/body/c02/motion_list.bin
  romfs/fighter/luigi/motion/body/c03/motion_list.bin
  romfs/fighter/luigi/motion/body/c04/motion_list.bin
  romfs/fighter/luigi/motion/body/c05/motion_list.bin
  romfs/fighter/luigi/motion/body/c06/motion_list.bin
  romfs/fighter/luigi/motion/body/c07/motion_list.bin
Labels: balance change

#381 zss nerfs
  romfs/fighter/common/param/fighter_param.prcxml
  src/szerosuit/acmd/aerials.rs
  src/szerosuit/acmd/ground.rs
  src/szerosuit/acmd/specials.rs
Labels: balance change

#380 ganon update
  src/ganon/acmd/ground.rs
Labels: balance change

#399 Changelog branch
  changelog/how2changelog.md
  changelog/mario.md
Labels: changelog

#401 mario changelog
  changelog/mario.md
Labels: changelog
