Repository chrispo-git/ult-s, pull requests merged in 2025-01, with the labels that each got.

#550 Bowser Dair Fix
  romfs/fighter/koopa/motion/body/c00/c05attackairlw.nuanmb
  romfs/fighter/koopa/motion/body/c01/c05attackairlw.nuanmb
  romfs/fighter/koopa/motion/body/c02/c05attackairlw.nuanmb
  romfs/fighter/koopa/motion/body/c03/c05attackairlw.nuanmb
  romfs/fighter/koopa/motion/body/c04/c05attackairlw.nuanmb
  romfs/fighter/koopa/motion/body/c05/c05attackairlw.nuanmb
  romfs/fighter/koopa/motion/body/c06/c05attackairlw.nuanmb
  romfs/fighter/koopa/motion/body/c07/c05attackairlw.nuanmb
  src/koopa/frame.rs
Labels: bug

#548 Sonic changes
  changelog/sonic.md
  src/sonic/acmd/aerials.rs
  src/sonic/acmd/tilts.rs
Labels: balance change

#545 Ganondorf Dthrow Removed
  romfs/fighter/ganon/motion/body/c00/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c00/motion_list.bin
  romfs/fighter/ganon/motion/body/c01/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c01/motion_list.bin
  romfs/fighter/ganon/motion/body/c02/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c02/motion_list.bin
  romfs/fighter/ganon/motion/body/c03/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c03/motion_list.bin
  romfs/fighter/ganon/motion/body/c04/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c04/motion_list.bin
  romfs/fighter/ganon/motion/body/c05/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c05/motion_list.bin
  romfs/fighter/ganon/motion/body/c06/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c06/motion_list.bin
  romfs/fighter/ganon/motion/body/c07/e01throwlw.nuanmb
  romfs/fighter/ganon/motion/body/c07/motion_list.bin
  src/ganon/acmd/throws.rs
Labels: balance change

#546 Jab Cancel Reductions
  src/common/jab.rs
Labels: engine change

#547 Fox Dthrow changes
  changelog/fox.md
  romfs/fighter/fox/motion/body/c00/motion_list.bin
  romfs/fighter/fox/motion/body/c01/motion_list.bin
  romfs/fighter/fox/motion/body/c02/motion_list.bin
  romfs/fighter/fox/motion/body/c03/motion_list.bin
  romfs/fighter/fox/motion/body/c04/motion_list.bin
  romfs/fighter/fox/motion/body/c05/motion_list.bin
  romfs/fighter/fox/motion/body/c06/motion_list.bin
  romfs/fighter/fox/motion/body/c07/motion_list.bin
  src/fox/acmd/throws.rs
Labels: balance change

#553 Bomberman downb nerf
  changelog/bomberman.md
  romfs/fighter/pacman/motion/body/c120/motion_list.bin
  src/bomberman/acmd/specials.rs
Labels: balance change

#554 Bomberman hurtbox
  src/bomberman/frame.rs
Labels: bug

#555 Peach Neutral Special bugfix
  src/peach/frame.rs
Labels: bug

#557 Dash Changes
  src/common/movement.rs
  src/util/mod.rs
Labels: engine change

#558 Lite fixes
  romfs/config_param.toml
  romfs/fighter/common/param/battle_object.prc
  romfs/ui/message/msg_name.xmsbt
  romfs/ui/param/database/ui_chara_db.prc
  romfs/ui/param/ui_chara_db.prc
  romfs/ui/param/ui_layout_db.prc
  src/common/movement.rs
Labels: bug, lite
